- name: Security  check 
  ansible.builtin.apt: 
    name: "{{ item }}"
    state: latest
  loop:
    - openssl
    - openssh
  ignore_errors: yes

- name: Docker installion check
  ansible.builtin.command: docker --version
  register: output
  ignore_errors: yes
- ansible.builtin.debug:
   var: output.failed

- name: Docker installation
  ansible.builtin.apt:
   name: docker.io
   state: present
  when: output.failed
  

